/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_sergiosuazo;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    public Chat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_newUser = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_newUser = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jd_chat = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_conversacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_usuarios = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setText("Nombre:");

        jLabel5.setText("Usuario:");

        jLabel6.setText("Contraseña:");

        jLabel7.setText("Fecha de Nacimiento: ");

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_newUserLayout = new javax.swing.GroupLayout(jd_newUser.getContentPane());
        jd_newUser.getContentPane().setLayout(jd_newUserLayout);
        jd_newUserLayout.setHorizontalGroup(
            jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_newUserLayout.createSequentialGroup()
                .addGroup(jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_newUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_newUserLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_newUserLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_newUser))
                                .addGroup(jd_newUserLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_contra)))
                            .addGroup(jd_newUserLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_newUserLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton3)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jd_newUserLayout.setVerticalGroup(
            jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_newUserLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(29, 29, 29))
        );

        ta_conversacion.setColumns(20);
        ta_conversacion.setRows(5);
        jScrollPane1.setViewportView(ta_conversacion);

        jl_usuarios.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_usuarios);

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane3.setViewportView(ta_mensaje);

        jButton4.setText("Send");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_chatLayout = new javax.swing.GroupLayout(jd_chat.getContentPane());
        jd_chat.getContentPane().setLayout(jd_chatLayout);
        jd_chatLayout.setHorizontalGroup(
            jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_chatLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_chatLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_chatLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(19, 19, 19)))
                        .addGap(50, 50, 50))))
        );
        jd_chatLayout.setVerticalGroup(
            jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_chatLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jd_chatLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addContainerGap())))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jButton1.setText("Log in");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Cuenta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel3.setText("No tienes cuenta? Crea una aqui:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pf_contra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            adminUsuario au = new adminUsuario("./Users.txt");
            au.cargarArchivo();
            Date fecha=dc_fecha.getDate();
            Date hoy=new Date();
            String date;
            date= fecha.toString();
            boolean repeat=false;
            for (int i = 0; i < au.getListaPersonas().size(); i++) {
                if(au.getListaPersonas().get(i).getUser().equals(tf_newUser.getText()))
                {
                    repeat=true;
                    break;
                }
            }
            
            if(hoy.getYear()-fecha.getYear()>=13&&!repeat)
            {
                au.getListaPersonas().add(new Usuario(tf_nombre.getText(), tf_newUser.getText(), tf_contra.getText(), date));
                au.escribirArchivo();
            }
            else
            {
                if(hoy.getYear()-fecha.getYear()<13)
                {
                    JOptionPane.showMessageDialog(this, "No tiene la edad para crear una cuenta");
                }
                else if(repeat)
                {
                    JOptionPane.showMessageDialog(this, "Ya existe ese usuario");
                }
                
            }
            JOptionPane.showMessageDialog(this, "Se creo el usuario exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al crear el ususario");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_newUser.setVisible(true);
        jd_newUser.pack();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        adminUsuario au=new adminUsuario("./Users.txt");
        boolean login=false;
        au.cargarArchivo();
        for (int i = 0; i < au.getListaPersonas().size(); i++) {
            if(au.getListaPersonas().get(i).getUser().equals(tf_user.getText()))
            {
                current=au.getListaPersonas().get(i);
                login=true;
                break;
            }
        }
        if(login)
        {
            jd_chat.setVisible(true);
            jd_chat.pack();
            DefaultListModel m=new DefaultListModel();
            for (int i = 0; i < au.getListaPersonas().size(); i++) {
                if(!au.getListaPersonas().get(i).equals(current))
                {
                    m.addElement(au.getListaPersonas().get(i));
                }
            }
            jl_usuarios.setModel(m);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        char opcion=' ';
        String texto;
        int ref=0;
        String resp="";
        int temp,temp2;
        texto=ta_mensaje.getText();
        String[] token=texto.split(" ");
        for (int i = 0; i < token.length; i++) {
            if(Character.isDigit(token[i].charAt(0)))
            {
                opcion=token[i].charAt(0);
            }
        }
        switch(opcion)
        {
            case '1':
            {
                for (int i = 0; i < token.length; i++) {
                    if(token[i].length()<=3)
                    {
                        String s=token[i]+"way";
                        resp+=s+" ";
                    }
                    else
                    {
                        if(token[i].charAt(0)=='a'||token[i].charAt(0)=='e'||token[i].charAt(0)=='i'||token[i].charAt(0)=='o'||token[i].charAt(0)=='u'||token[i].charAt(0)=='A'||token[i].charAt(0)=='E'||token[i].charAt(0)=='I'||token[i].charAt(0)=='O'||token[i].charAt(0)=='U')
                        {
                            String s=token[i]+"ay";
                            resp+=s+" ";
                        }
                        else
                        {
                            for (int j = 0; j < token[i].length(); j++) {
                                if(token[i].charAt(j)=='a'||token[i].charAt(j)=='e'||token[i].charAt(j)=='i'||token[i].charAt(j)=='o'||token[i].charAt(j)=='u')
                                {
                                    ref=j;
                                    break;
                                }
                            }
                            for (int j = ref; j < token[i].length(); j++) {
                                resp+=token[i].charAt(j);
                            }
                            for (int j = 0; j < ref; j++) {
                                resp+=token[i].charAt(j);
                            }
                            resp+="ay ";
                        }
                    }
                }
                ta_conversacion.setText(current.getUser()+": "+texto+"\n easyCypher: "+resp+"\n");
                break;
            }
            case'2':
            {
                for (int i = 0; i < texto.length()-1; i++) {
                    if(texto.charAt(i)!=' ')
                    {
                        temp=texto.charAt(i);
                        resp+=temp+" ";
                    }
                }
                ta_conversacion.setText(current.getUser()+": "+texto+"\n easyCypher: "+resp+"\n");
                break;
            }
            case'3':
            {
                for (int i = 0; i < texto.length()-1; i++) {
                    if(texto.charAt(i)!=' ')
                    {
                        temp=texto.charAt(i);
                        if(temp<=77)
                        {
                            temp2=77-temp;
                            temp2=+78;
                            resp+=(char)temp2;
                        }
                        if(temp>=78&&temp<97)
                        {
                            temp-=78;
                            temp2=77-temp;
                            resp+=(char)temp2;
                        }
                        if(temp<=109&&temp>=97)
                        {
                            temp2=109-temp;
                            temp2+=110;
                            resp+=(char)temp2;
                        }
                        if(temp>=110)
                        {
                            temp-=110;
                            temp2=109-temp;
                            resp+=(char)temp2;
                        }
                    }
                    else
                    {
                        resp+=' ';
                    }
                }
                ta_conversacion.setText(current.getUser()+": "+texto+"\n easyCypher: "+resp+"\n");
                break;
            }
            case'4':
            {
                break;
            }
            default:
            {
                break;
            }
            
        }
        ta_mensaje.setText("");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        guardarArchivo();
        jd_chat.setVisible(false);
        ta_conversacion.setText("");
        ta_mensaje.setText("");
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }
    public void guardarArchivo(){
        try
        {
            String nombre="";
            JFileChooser file=new JFileChooser();
            file.showSaveDialog(this);
            File guarda =file.getSelectedFile();

            if(guarda !=null)
            {
              FileWriter  save=new FileWriter(guarda+".txt");
              save.write(ta_conversacion.getText());
              save.close();
              JOptionPane.showMessageDialog(null,
                   "El archivo se a guardado Exitosamente",
                       "Información",JOptionPane.INFORMATION_MESSAGE);
            }
        }
     catch(IOException ex)
     {
      JOptionPane.showMessageDialog(null,
           "Su archivo no se ha guardado",
              "Advertencia",JOptionPane.WARNING_MESSAGE);
     }
 }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_chat;
    private javax.swing.JDialog jd_newUser;
    private javax.swing.JList<String> jl_usuarios;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JTextArea ta_conversacion;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_newUser;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables

    Usuario current;
    

}
